author: Xzonn
name: 《夏日重现 Another Horizon》汉化发布
timezone: Asia/Shanghai
url: https://xzonn.top/STRAHChsLocalization
defaults:
  - values:
      layout: "default"
exclude:
  - Debug/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - jsconfig.json
  - README.md
markdown: kramdown
plugins:
  - jekyll-relative-links
  - jekyll-sass-converter
repository: Xzonn/STRAHChsLocalization
sass:
  sass_dir: assets/css
  load_paths: 
    - assets/css
    - node_modules
  sourcemap: always
  style: compressed
relative_links:
  collections: true