name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 1
      - name: Create Patch
        run: |
          bin/STRAHChsLocalizationHelper
          compress-archive out/01005940182ec000/ out/patch.zip -force
      - name: Upload patch
        uses: actions/upload-artifact@v3
        with:
          name: patch
          path: |
            out/01005940182ec000/
      - run: tail -n +2 README.md > NEW_README.md
      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "out/patch.zip"
          body: |
            [![Convert csv to json](https://github.com/Xzonn/STRAHChsLocalization/actions/workflows/convert.yml/badge.svg)](https://github.com/Xzonn/STRAHChsLocalization/actions/workflows/convert.yml)

            本页面下方的链接为自动构建并发布的开发版本补丁。此版本补丁可能存在较多问题，仅供测试使用。
          name: "《夏日重现 Another Horizon》汉化"
          tag: publish
          token: ${{ secrets.GITHUB_TOKEN }}