name: Build on push

on:
  push:
    branches: 
      - master
      - test
    paths-ignore:
      - '*.md'
      - '**/.gitignore'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.ref_name }}